GET localhost:8080/
Content-Type: application/json
###

GET localhost:8080/api/read
Content-Type: application/json
###

GET localhost:8080/api/read/15
Content-Type: application/json
###

POST localhost:8080/api/submit
Accept: application/json

{
       "name":"sajt",
       "companyName":"ZOP Games"
       "category":"0",
       "origin":0,
       "pellet":true,
       "recycled":true,
       "reused":true,
       "renewable":true,
       "recyclable":true,
       "hasInsulation":true,
       "co2":2,
       "ch4":23,
       "reauseWaste":1
}